### ISSUE TITLE
Google PageSpeed Insights >> Optimise the Site!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dwyl-site#447]
At present the dwyl.com website scores quite poorly on the Google PageSpeed checker:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdwyl.com
![image](https://user-images.githubusercontent.com/194400/36171563-05247552-10fb-11e8-8707-b38ff922e28e.png)

## Todo / Tasks

+ [ ] Optimise Images: https://developers.google.com/speed/docs/insights/OptimizeImages
+ [ ] Move JS (_including GTM_) to footer.
+ [ ] Minify and compress CSS & JS files
+ [ ] Add cache headers

This _might_ be improved by https://github.com/dwyl/dwyl-site/issues/270 (_templating_)
so only focus on _this_ issue once #270 is complete.
